#!/bin/sh
# shellcheck disable=SC2155

get_cpu_freq() {
  local value="$(cat /sys/devices/system/cpu/cpufreq/policy0/scaling_cur_freq 2>/dev/null)"
  [ -n "$value" ] || value="0"
  echo "$value"
}

get_cpu_governor() {
  local value="$(cat /sys/devices/system/cpu/cpufreq/policy0/scaling_governor 2>/dev/null)"
  [ -n "$value" ] || value="unknown"
  echo "$value"
}

get_cpu_temp() {
  local value="$(cat /sys/class/thermal/thermal_zone*/temp 2>/dev/null | sort -n | tail -1)"
  [ -n "$value" ] || value="-1"
  echo "$value"
}

get_wifi_temp() {
  local value="$(cat /sys/class/ieee80211/phy*/hwmon*/temp*_input 2>/dev/null | sort -n | tail -1)"
  [ -n "$value" ] || value="-1"
  echo "$value"
}

get_cpu_usage() {
  local value="$(top -b -n1 | awk '/^CPU/ { print 100-$8 }')"
  [ -n "$value" ] || value="-1"
  echo "$value"
}

case "$1" in
  cpu_freq)
    get_cpu_freq
    ;;
  cpu_governor)
    get_cpu_governor
    ;;
  cpu_temp)
    get_cpu_temp | awk '{ printf("%.1f\n", $1/1000) }'
    ;;
  wifi_temp)
    get_wifi_temp | awk '{ printf("%.1f\n", $1/1000) }'
    ;;
  cpu_usage)
    get_cpu_usage
    ;;
  *)
    echo "Usage: $0 {cpu_freq|cpu_governor|cpu_temp|wifi_temp|cpu_usage}"
    exit 1
    ;;
esac
